site_name: NopAccelerate Docs
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.tracking
    - navigation.path
    - navigation.breadcrumbs
    - header.autohide
plugins:
  - search
  - awesome-pages
extra:
  footer: © 2025 NopAccelerate • Built with ❤️ by NopAccelerate Team
nav:
  - Home: index.md
  - Display Reward Plugin:
      - Overview: displayReward/index.md
      - Features: displayReward/Feature.md
      - Version History: 
          - Overview: displayReward/History.md
          - Version 49.0.0: displayReward/49.0.0.md
          - Version 1.3.0: displayReward/1.3.0.md         
          - Version 1.2.0: displayReward/1.2.0.md          
          - Version 1.1.0: displayReward/1.1.0.md          
          - Version 1.0.1: displayReward/1.0.1.md
          - Version 1.0.0: displayReward/1.0.0.md
          
      - Installation:
          - Licensing: displayReward/Licence.md
          - Configuration: displayReward/Configuration.md
          - Scenerios of Use: displayReward/senerioOfUse.md
          - Help: displayReward/Help.md

  - Bundle Discount Plugin:
      - Overview: bundleDiscount/index.md
      - Features: bundleDiscount/features.md
      - Version History: 
          - Overview: bundleDiscount/version-history.md
          - Version 1.0.0: bundleDiscount/1.0.0.md
          - Version 1.0.1: bundleDiscount/1.0.1.md
      - Installation:
          - Licensing: bundleDiscount/getting-started.md

  - NopAccelerate Plus:
      - Overview: NopAcceleratePlus/index.md
      - Support Document:
        - Overview: NopAcceleratePlus/SupportDocOverview.md
        - nopAccelerate Plus Pro Installation: NopAcceleratePlus/nopAcceleratePlusProInstallation.md
        - JAVA Setup: NopAcceleratePlus/JAVASetup.md
        - SOLR Setup:
          - Solr Setup Steps: NopAcceleratePlus/SOLRSetup.md
          - What is SOLR ?: NopAcceleratePlus/SOLR.md
          - How to Start/Stop/Restart SOLR ?: NopAcceleratePlus/StartSolr.md
          - Creating a new Core: NopAcceleratePlus/CreateCore.md
          - How to Delete Core: NopAcceleratePlus/DeleteCore.md
          - How to Reload Core: NopAcceleratePlus/ReloadCore.md
          - How to Delete Indexed data: NopAcceleratePlus/DeleteIndexData.md
          - Start Solr on System Startup: NopAcceleratePlus/StartSolronSystemStartup.md
      - Version History: 
        - Overview: NopAcceleratePlus/version-history.md        
        # - Version 0.3.0.850: NopAcceleratePlus/0.3.0.850.md
        # - Version 0.3.0.850: NopAcceleratePlus/0.3.0.850.md
        # - Version 0.3.0.850: NopAcceleratePlus/0.3.0.850.md
        - Version 0.4.0: NopAcceleratePlus/0.4.0.md
        - Version 0.3.0.1115: NopAcceleratePlus/0.3.0.1115.md
        - Version 0.3.0.1056: NopAcceleratePlus/0.3.0.1056.md
        - Version 0.3.0.925: NopAcceleratePlus/0.3.0.925.md
        - Version 0.3.0.862: NopAcceleratePlus/0.3.0.862.md
        - Version 0.3.0.850: NopAcceleratePlus/0.3.0.850.md
        - Version 0.3.0.805: NopAcceleratePlus/0.3.0.805.md
        - Version 0.3.0.744: NopAcceleratePlus/0.3.0.744.md
        - Version 0.3.0.727: NopAcceleratePlus/0.3.0.727.md
        - Version 0.3.0.696: NopAcceleratePlus/0.3.0.696.md
        - Version 0.3.0.666: NopAcceleratePlus/0.3.0.666.md
        - Version 0.3.0: NopAcceleratePlus/0.3.0.md
      - Technical FAQ's: 
        - Technical FAQ's overview: NopAcceleratePlus/Technical FAQ's.md
        - Error while indexing : NopAcceleratePlus/ErrorWhileIndexing.md
        - Setup Core on Shared Server : NopAcceleratePlus/SetupCoreOnSharedServer.md
        - Connect To Solr : NopAcceleratePlus/ConnectToSolr.md
        - TimeOut Expiration : NopAcceleratePlus/TimeOutExpiration.md
        - Category and Manufacturer Navigation : NopAcceleratePlus/Category&ManufacutreNavigation.md
        - Search with Synonyms : NopAcceleratePlus/SearchWithSynonyms.md
        - Facet Filter with % : NopAcceleratePlus/FacetFilterWith%.md
        - Solr as Service : NopAcceleratePlus/SolrService.md
        - Licensing Issues : NopAcceleratePlus/LicensingIssues.md
        - Responsive filter : NopAcceleratePlus/ResponsiveFilter.md
        - Font Error : NopAcceleratePlus/FontError.md
        - WebRequest: NopAcceleratePlus/WebRequest.md
      - Help : NopAcceleratePlus/Help.md
